<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="50424" started-at="2020-07-05T12:02:07Z" finished-at="2020-07-05T12:02:58Z">
    <groups>
    </groups>
    <test name="Test Case One" duration-ms="24951" started-at="2020-07-05T12:02:07Z" finished-at="2020-07-05T12:02:32Z">
      <class name="testCases.TC_001">
        <test-method status="PASS" signature="launchBrowser()[pri:0, instance:testCases.TC_001@57f23557]" name="launchBrowser" is-config="true" duration-ms="12499" started-at="2020-07-05T12:02:07Z" finished-at="2020-07-05T12:02:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method status="FAIL" signature="testCase001(java.lang.String, java.lang.String)[pri:0, instance:testCases.TC_001@57f23557]" name="testCase001" duration-ms="11670" started-at="2020-07-05T12:02:20Z" data-provider="getData" finished-at="2020-07-05T12:02:31Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[CASUAL DRESSES]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Product successfully added to your shopping cart]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [Product successfully added to your shopping cart]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [Product successfully added to your shopping cart]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testCases.TC_001.testCase001(TC_001.java:69)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCase001 -->
        <test-method status="PASS" signature="quitBrowser()[pri:0, instance:testCases.TC_001@57f23557]" name="quitBrowser" is-config="true" duration-ms="724" started-at="2020-07-05T12:02:31Z" finished-at="2020-07-05T12:02:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quitBrowser -->
      </class> <!-- testCases.TC_001 -->
    </test> <!-- Test Case One -->
    <test name="Test Case Two" duration-ms="13070" started-at="2020-07-05T12:02:32Z" finished-at="2020-07-05T12:02:46Z">
      <class name="testCases.TC_002">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:testCases.TC_002@130f889]" name="startBrowser" is-config="true" duration-ms="11931" started-at="2020-07-05T12:02:32Z" finished-at="2020-07-05T12:02:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="PASS" signature="testTitle()[pri:0, instance:testCases.TC_002@130f889]" name="testTitle" duration-ms="6" started-at="2020-07-05T12:02:44Z" finished-at="2020-07-05T12:02:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTitle -->
        <test-method status="PASS" signature="quiteBrowser()[pri:0, instance:testCases.TC_002@130f889]" name="quiteBrowser" is-config="true" duration-ms="1128" started-at="2020-07-05T12:02:44Z" finished-at="2020-07-05T12:02:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quiteBrowser -->
      </class> <!-- testCases.TC_002 -->
    </test> <!-- Test Case Two -->
    <test name="Test Case Three" duration-ms="11959" started-at="2020-07-05T12:02:46Z" finished-at="2020-07-05T12:02:58Z">
      <class name="testCases.TC_003">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:testCases.TC_003@33b37288]" name="startBrowser" is-config="true" duration-ms="11244" started-at="2020-07-05T12:02:46Z" finished-at="2020-07-05T12:02:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="FAIL" signature="testTitle()[pri:0, instance:testCases.TC_003@33b37288]" name="testTitle" duration-ms="25" started-at="2020-07-05T12:02:57Z" finished-at="2020-07-05T12:02:57Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [My Store..] but found [My Store]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [My Store..] but found [My Store]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testCases.TC_003.testTitle(TC_003.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTitle -->
        <test-method status="PASS" signature="quiteBrowser()[pri:0, instance:testCases.TC_003@33b37288]" name="quiteBrowser" is-config="true" duration-ms="678" started-at="2020-07-05T12:02:57Z" finished-at="2020-07-05T12:02:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quiteBrowser -->
      </class> <!-- testCases.TC_003 -->
    </test> <!-- Test Case Three -->
  </suite> <!-- Suite -->
</testng-results>
